/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2023-05-05 08:09:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.bean.UserBean;
import java.util.Iterator;
import java.util.List;

public final class UserListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1683253523823L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1682682817231L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.bean.UserBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		//	String name = (String) request.getAttribute("name");//-->req whitout session
		String name = (String) session.getAttribute("name");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t");

				if (name != null) {
			
      out.write("\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t<h3><b><a href=\"LoginCtl?operation=logout\">LogOut</a> </h3>");

 	} else {
 
      out.write(' ');

 	}
 
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"90%\"></td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t<h1 align=\"Right\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/Rays.jpg\" height=\"100\">\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t");

					if (name != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\tHi,");
      out.print(name);
      out.write("</h3> ");

 	} else {
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h3>hi,Gust</h3> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t");

				if (name != null) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td colspan=\"2\"><b><a href=\"UserResgistrationCtl\">Add\r\n");
      out.write("\t\t\t\t\t\tUser</a> | <a href=\"UserListCtl.do\">User List</a></b></td>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"UserListCtl.do\" method=\"post\">\r\n");
      out.write("\t\r\n");
      out.write("\t");

		List list = (List) request.getAttribute("List");
		Iterator it = list.iterator();
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<th>Name :</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t<td><a href=\"UserListCtl.do\" ><input type=\"submit\" name=\"operation\" value=\"search\"></td>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table border=\"2\" style=\"width: 1520px\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Id</th>\r\n");
      out.write("\t\t\t<th>FirstName</th>\r\n");
      out.write("\t\t\t<th>LastName</th>\r\n");
      out.write("\t\t\t<th>LoginId</th>\r\n");
      out.write("\t\t\t<th>Password</th>\r\n");
      out.write("\t\t\t<th>MobileNumber</th>\r\n");
      out.write("\t\t\t<th>Edit</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			while (it.hasNext()) {
				UserBean bean1 = (UserBean) it.next();
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(bean1.getId());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bean1.getFirstName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bean1.getLastName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bean1.getLoginId());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bean1.getPassword());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bean1.getMobileNumber());
      out.write("</td>\r\n");
      out.write("\t\t\t<td><a href=\"UserResgistrationCtl?id=");
      out.print(bean1.getId());
      out.write("\">Edit</a>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 
			}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<hr>\r\n");
      out.write("    <CENTER>\r\n");
      out.write("    <td></td>\r\n");
      out.write("        <H3>(c) Copyrights SunilOS Infotech Pvt. Ltd.</H3>\r\n");
      out.write("    </CENTER>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
